moved functions to new file

diff --git a/bashconf/functions b/bashconf/functions
--- a/bashconf/functions
+++ b/bashconf/functions
@@ -1,5 +1,59 @@
 #!/usr/bin/bash
 
+# vim:fileencoding=utf-8:foldmethod=marker
+
 # functions for bashrc
 #
 # author: RilCritch
+
+# show the list of packages that need this package - depends mpv as example
+depends () {
+	search=$(echo "$1")
+	sudo pacman -Sii $search | grep "Required" | sed -e "s/Required By     : //g" | sed -e "s/  /\n/g"
+}
+
+# navigation moving up directories
+up () {
+  local d=""
+  local limit="$1"
+
+  # Default to limit of 1
+  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
+    limit=1
+  fi
+
+  for ((i=1;i<=limit;i++)); do
+    d="../$d"
+  done
+
+  # perform cd. Show error if cd fails
+  if ! cd "$d"; then
+    echo "Couldn't go up $limit dirs.";
+  fi
+}
+
+# EXtractor for all kinds of archives
+# usage: ex <file>
+ex() {
+	if [ -f $1 ]; then
+		case $1 in
+      *.tar.bz2) tar xf $1 ;;
+      *.tar.gz) tar xzf $1 ;;
+      *.bz2) bunzip2 $1 ;;
+      *.rar) unrar x $1 ;;
+      *.gz) gunzip $1 ;;
+      *.tar) tar xf $1 ;;
+      *.tbz2) tar xf $1 ;;
+      *.tgz) tar xzf $1 ;;
+      *.zip) unzip $1 ;;
+      *.Z) uncompress $1 ;;
+      *.7z) 7z x $1 ;;
+      *.deb) ar x $1 ;;
+      *.tar.xz) tar xf $1 ;;
+      *.tar.zst) tar xf $1 ;;
+      *) echo "'$1' cannot be extracted via ex()" ;;
+		esac
+	else
+		echo "'$1' is not a valid file"
+	fi
+}
